### ISSUE TITLE
關於協作

### ISSUE THREAD

**Issue by nova1529** [codebayin/Dust.An.Elysian.Tail.zh_TW#1]
不好意思

請問該怎麼起手呢？
我已經將專案匯入到source tree內
但是下一步就沒有頭緒啦（抓頭）

懇請指點QQ

**Comment by nickexe** [comment]
如果已經匯到 SourceTree 了，建好分支同步一下( 流程 3~7)就可以開始翻譯了，
Dust.zreproj 就是專案檔，用 Zeta Resource Editor 打開就可以了，
只要看到中文那邊空的就是還沒翻譯的，你可以選還沒翻的開始，說一下哪些檔案你要翻就行了，
免得有人翻到一樣的，Strings_開頭的檔案我都認了。
我有寫基本的協作流程在最前面，目前不打算從頭教 git 怎麼用，Google 可以找到很多教學。

問題或討論的話請在 Discord 聊天室，不要發在 issue 裡。
