### ISSUE TITLE
commit問題

### ISSUE THREAD

**Issue by MofuMoca** [codebayin/Dust.An.Elysian.Tail.zh_TW#14]
因為我修改完成後
是有三個檔案被修改
分別是：
- translation/Dust.zreproj
- translation/Dialogue_SmoBop.zh-TW.resx
- translation/Dialogue_SmoBop.resx

看一下commit紀錄好像都沒有提交其他兩個
想請問一下要怎樣提交？

**Comment by nickexe** [comment]
commit 的時候可以決定要哪些檔案，只要列入 zh-TW 的檔案就好
