### ISSUE TITLE
_

### ISSUE THREAD

**Issue by anythink-wx** [codebayin/Dust.An.Elysian.Tail.zh_TW#8]
需要我帮忙整理一份简体中文的语言包吗？

**Comment by nickexe** [comment]
感謝你的心意，不過我目前沒有做簡體版的計畫

**Comment by anythink-wx** [comment]
是有什么不一样的地方吗？我已经整理出来部分文件，提交了pull request ，请看看。

**Comment by nickexe** [comment]
主要問題是專案檔我目前不打算更動，加檔案就必須更動到，
再來正體的文本並非最終定案內容，隨時可能改動，簡體不一定能確實同步到，
最後會很亂，要弄也是等全部完成之後再說。

**Comment by anythink-wx** [comment]
是说除了这些resx文件外还要处理别的更复杂的事情么？同步这块问题到还好，最后我可以写脚本统一处理。如果需要，随时联系我~
